version: '3.1'

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    container_name: c_bank_app
    ports:
      - 3000:3000

  postgres:
    image: postgres
    container_name: c_bank_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: dbuser123
      POSTGRES_DB: bank
